import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AreaChart, Area, ResponsiveContainer, Tooltip } from 'recharts';
import { Activity, AlertTriangle, Bell, BrainCircuit, ChevronRight, CircleHelp, CloudSun, Droplets, HeartPulse, Home, Leaf, LineChart, Moon, Plus, Settings, ShieldCheck, Siren, Sparkles, Thermometer, UserRound, Wind, X } from 'lucide-react';
import './styles.css';

const trendData = [
  { time: '6am', heart: 67, spo2: 98, temp: 36.6 }, { time: '8am', heart: 71, spo2: 98, temp: 36.6 },
  { time: '10am', heart: 80, spo2: 97, temp: 36.8 }, { time: '12pm', heart: 78, spo2: 98, temp: 36.8 },
  { time: '2pm', heart: 84, spo2: 98, temp: 36.9 }, { time: '4pm', heart: 76, spo2: 98, temp: 36.8 },
  { time: 'Now', heart: 78, spo2: 98, temp: 36.8 },
];

export function getRiskPrediction(data) {
  return { riskScore: data.temperature > 37.5 ? 82 : 18, riskLevel: data.temperature > 37.5 ? 'Caution' : 'Low risk', confidence: data.temperature > 37.5 ? 87 : 92, pattern: data.temperature > 37.5 ? 'Potential heat-stress pattern' : 'Stable personal pattern', anomalyDetected: data.temperature > 37.5 };
}

const nav = [{ label: 'Home', icon: Home }, { label: 'AI Insights', icon: BrainCircuit }, { label: 'Health', icon: HeartPulse }, { label: 'Trends', icon: LineChart }, { label: 'Environment', icon: CloudSun }, { label: 'Alerts', icon: Bell }, { label: 'Emergency', icon: Siren }, { label: 'Settings', icon: Settings }];
const vitals = [{ label: 'Heart rate', value: '78', unit: 'BPM', icon: HeartPulse, shade: 'coral' }, { label: 'Blood oxygen', value: '98', unit: '% SpO₂', icon: Activity, shade: 'blue' }, { label: 'Body temperature', value: '36.8', unit: '°C', icon: Thermometer, shade: 'orange' }, { label: 'Current activity', value: 'Walking', unit: 'Light movement', icon: Activity, shade: 'purple' }];

function Card({ children, className = '' }) { return <section className={`card ${className}`}>{children}</section>; }
function SectionTitle({ eyebrow, title, action }) { return <div className="section-title"><div>{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2></div>{action}</div>; }
function MiniRisk({ title, score, note }) { return <div className="mini-risk"><div><strong>{title}</strong><span>{note}</span></div><b>{score}<small>/100</small></b><div className="bar"><i style={{ width: `${score}%` }} /></div><em>Low</em></div>; }

function Dashboard() {
  const [active, setActive] = useState('Home'); const [period, setPeriod] = useState('1D'); const [sos, setSos] = useState(false); const [sent, setSent] = useState(false); const [demoRisk, setDemoRisk] = useState(false);
  const prediction = getRiskPrediction({ temperature: demoRisk ? 38 : 36.8 });
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><HeartPulse size={20}/></div><span>pulsely</span></div><nav>{nav.map(({label, icon: Icon}) => <button key={label} className={active === label ? 'active' : ''} onClick={() => setActive(label)}><Icon size={18}/><span>{label}</span>{label === 'Alerts' && <i className="nav-dot"/>}</button>)}</nav><div className="sidebar-foot"><div className="local"><span/> Local analysis ready</div><button className="profile"><div className="avatar">AR</div><span><b>Ananya Rao</b><small>Personal plan</small></span><ChevronRight size={15}/></button></div></aside>
    <main><header><div><p className="date">Friday, August 29</p><h1>Good evening, Ananya.</h1><p className="subtitle">Your health, <i>understood.</i></p></div><div className="header-actions"><button className="demo-toggle" onClick={() => setDemoRisk(!demoRisk)}><span className={demoRisk ? 'warning-dot' : ''}/> Demo data</button><button className="icon-button"><Bell size={19}/><i/></button><div className="avatar large">AR</div></div></header>
      {active !== 'Home' && <div className="page-notice"><Sparkles size={18}/><span><b>{active}</b> is ready for the live health-data interface. This demo keeps the most relevant overview visible below.</span></div>}
      <div className="overview-grid">
        <Card className={`insight ${prediction.anomalyDetected ? 'caution' : ''}`}><div className="insight-top"><div><span className="eyebrow"><BrainCircuit size={13}/> AI health insight</span><p>{prediction.anomalyDetected ? 'An unusual pattern needs your attention.' : 'Your current health pattern appears stable.'}</p></div><span className="sim">SIMULATED AI</span></div><div className="insight-content"><div className="score-ring"><svg viewBox="0 0 120 120"><circle cx="60" cy="60" r="48"/><circle className="progress" cx="60" cy="60" r="48" style={{strokeDashoffset: 302 - (302 * prediction.riskScore / 100)}}/></svg><div><b>{prediction.riskScore}</b><small>/ 100</small></div></div><div className="insight-stats"><div><span>Risk assessment</span><strong>{prediction.riskLevel}</strong></div><div><span>Pattern</span><strong>{prediction.pattern}</strong></div><div><span>Confidence</span><strong>{prediction.confidence}%</strong></div></div><button className="round-arrow"><ChevronRight size={20}/></button></div></Card>
        <Card className="anomaly"><SectionTitle eyebrow="Live interpretation" title="Anomaly detection"/><div className="anomaly-status"><div className="status-icon"><ShieldCheck size={24}/></div><div><strong>{prediction.anomalyDetected ? 'Potential abnormal pattern' : 'No significant anomaly detected'}</strong><p>{prediction.anomalyDetected ? 'A combination of elevated heart rate and temperature was detected.' : 'Your current signals align with your personal baseline.'}</p></div></div><div className="signal-row"><span><HeartPulse/> {demoRisk ? '105' : '78'} BPM</span><span><Thermometer/> {demoRisk ? '38.0' : '36.8'} °C</span><span><Activity/> Walking</span></div><button className="text-link">View pattern detail <ChevronRight size={15}/></button></Card>
      </div>
      <div className="section-head"><SectionTitle eyebrow="Inputs to your personal health model" title="Today’s vital data"/><span className="updated">Updated just now</span></div><div className="vitals-grid">{vitals.map(({label,value,unit,icon:Icon,shade})=><Card className="vital" key={label}><div className={`vital-icon ${shade}`}><Icon size={19}/></div><span>{label}</span><strong>{value}</strong><small>{unit}</small><div className="spark"><i/><i/><i/><i/><i/><i/></div></Card>)}</div>
      <div className="content-grid"><Card className="trends"><SectionTitle eyebrow="Personal health patterns" title="Health trends" action={<div className="filter">{['1D','7D','30D'].map(x=><button className={period===x?'selected':''} onClick={()=>setPeriod(x)} key={x}>{x}</button>)}</div>}/><div className="chart-heading"><div><b>Heart rate</b><strong>78 <small>BPM</small></strong></div><span><i/> Within your usual range</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trendData}><defs><linearGradient id="heart" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#ef6b62" stopOpacity=".26"/><stop offset="100%" stopColor="#ef6b62" stopOpacity="0"/></linearGradient></defs><Tooltip contentStyle={{borderRadius:12,border:'none',boxShadow:'0 8px 20px #1b2b3518'}}/><Area type="monotone" dataKey="heart" stroke="#ed6b63" strokeWidth={3} fill="url(#heart)"/></AreaChart></ResponsiveContainer></div><div className="chart-labels">{trendData.map(x=><span key={x.time}>{x.time}</span>)}</div></Card>
        <Card className="why"><SectionTitle eyebrow="Explainable AI" title="Why this result?"/><p className="why-intro">The model compares signals together, not in isolation.</p><div className="factors"><span><HeartPulse/> Heart rate<br/><b>+6 BPM from baseline</b></span><i>+</i><span><Thermometer/> Body temperature<br/><b>Within normal range</b></span><i>+</i><span><CloudSun/> Environment<br/><b>Warm, comfortable</b></span></div><div className="model-result"><BrainCircuit size={19}/><span>Model interpretation</span><b>Stable personal pattern</b></div></Card></div>
      <div className="three-grid"><Card><SectionTitle eyebrow="Personalized reference" title="Your baseline"/><div className="baseline"><div><span>Resting heart rate</span><b>72 <small>BPM</small></b></div><div><span>Typical SpO₂</span><b>98<small>%</small></b></div><div><span>Typical temperature</span><b>36.7<small>°C</small></b></div></div><div className="baseline-note"><ShieldCheck size={17}/> Current readings are within your personal baseline.</div></Card><Card><SectionTitle eyebrow="Predictive context" title="Risk assessment"/><div className="risks"><MiniRisk title="Heat stress" score={18} note="Environment and activity are balanced."/><MiniRisk title="Respiratory risk" score={12} note="Oxygen level is consistent."/><MiniRisk title="Cardiovascular stress" score={15} note="Heart-rate trend is normal."/></div></Card><Card className="environment"><SectionTitle eyebrow="Contributes to AI analysis" title="Environmental context"/><div className="env-stats"><span><Thermometer/>31°<small>Outside</small></span><span><Droplets/>58%<small>Humidity</small></span><span><Leaf/>42<small>Good AQI</small></span></div><p><Wind size={15}/> Conditions are currently within a comfortable range.</p></Card></div>
      <div className="content-grid lower"><Card><SectionTitle eyebrow="AI-guided next steps" title="Personalized recommendations"/><div className="recommendations"><div><div className="rec-icon aqua"><Droplets/></div><span><b>Stay hydrated</b><small>Maintain regular hydration for today’s conditions.</small></span><ChevronRight size={17}/></div><div><div className="rec-icon lavender"><Moon/></div><span><b>Keep your evening light</b><small>Your recent activity level is elevated.</small></span><ChevronRight size={17}/></div><div><div className="rec-icon yellow"><CloudSun/></div><span><b>Mind the heat</b><small>Limit prolonged exposure to high temperatures.</small></span><ChevronRight size={17}/></div></div></Card><Card><SectionTitle eyebrow="Health event timeline" title="Alerts" action={<button className="text-link">View all</button>}/><div className="alerts"><div><span className="info">INFO</span><p><b>No critical alerts</b><small>Your latest health analysis is clear.</small></p><time>Now</time></div><div><span className="caution-badge">CAUTION</span><p><b>Potential heat-stress pattern</b><small>Resolved after rest</small></p><time>10:15 AM</time></div><div><span className="info">INFO</span><p><b>SpO₂ deviation detected</b><small>Returned to baseline</small></p><time>9:42 AM</time></div></div></Card></div>
      <Card className="safety"><div><div className="safety-icon"><Siren/></div><div><span className="eyebrow">Safety check</span><h2>Fall & distress detection</h2><p>No fall or medical-distress event detected. This simulated status will later be connected to wearable inputs.</p></div></div><div className="safety-status"><span><ShieldCheck/> All clear</span><button onClick={()=>setSos(true)}>Emergency SOS</button></div></Card>
      <Card className="privacy"><div className="privacy-icon"><ShieldCheck/></div><div><h3>Your health data stays private.</h3><p>This interface is designed for local, privacy-preserving analysis when the future AI system is connected.</p></div><div className="privacy-tags"><span>Local processing</span><span>Private by design</span><span>Offline ready</span></div></Card>
    </main>
    <nav className="mobile-nav">{nav.slice(0,5).map(({label,icon:Icon})=><button key={label} className={active===label?'active':''} onClick={()=>setActive(label)}><Icon size={19}/><small>{label==='AI Insights'?'AI':label}</small></button>)}</nav>
    {sos && <div className="modal-backdrop" onMouseDown={()=>setSos(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setSos(false)}><X/></button><div className="sos-icon"><Siren/></div><span className="eyebrow">Emergency assistance</span><h2>{sent ? 'SOS alert prepared' : 'Send an SOS alert?'}</h2><p>{sent ? 'Demo complete. No contact was notified.' : 'This is a demo interface. No message will be sent.'}</p>{!sent ? <div className="modal-actions"><button onClick={()=>setSos(false)}>Cancel</button><button className="send" onClick={()=>setSent(true)}>Send SOS</button></div> : <button className="done" onClick={()=>{setSent(false);setSos(false)}}>Done</button>}</div></div>}
  </div>;
}
createRoot(document.getElementById('root')).render(<Dashboard/>);
